### ISSUE TITLE
UnboundLocalError on checking segment index tables for invalid file

### ISSUE THREAD

**Issue by bradh** [dstl/NPIF-Sleuth#3]
```
Traceback (most recent call last):
  File "./NPIF Sleuth.py", line 107, in <module>
    main()
  File "./NPIF Sleuth.py", line 101, in main
    retval = NPIF_Extract(fname)
  File "./NPIF Sleuth.py", line 86, in NPIF_Extract
    a.file_error_checks()
  File "/home/bradh/coding/NPIF-Sleuth/NPIF.py", line 5622, in file_error_checks
    self.check_segmentindextables()
  File "/home/bradh/coding/NPIF-Sleuth/NPIF.py", line 6512, in check_segmentindextables
    endoff = self.packetstarts[last] - self.frontbytelen + plen
UnboundLocalError: local variable 'last' referenced before assignment
```

The file numbers are a bit different in my version, but the relevant part of the code is
``` python
      for p in reversed(self.packets):
          # need to ignore postable and End of Segment tables in this calculation
          if p.hdr.segmentnum == seg and p.hdr.ambleflag == 0:
              if p.hdr.tablecode != self.DT_End_Segment_Marker_DT:
                  last = p.hdr.packetnum
                  tt = p.hdr.timetag
                  plen = p.hdr.claimlen
                  break
      endoff = self.packetstarts[last] - self.frontbytelen + plen
```

Occurs on this file:
```
0000000 0d 79 ab 21 6f 34 1a 72 b9 1c 03 08 01 30 00 00  >.y.!o4.r.....0..<
0000020 01 00 00 00 00 50 00 00 00 00 00 00 00 00 00 00  >.....P..........<
0000040 0f 3d 00 00 00 00 00 00 06 9c 00 00 00 00 00 00  >.=..............<
0000060 2b 8c 00 00 00 00 01 1e 33 81 07 d3 03 1a 10 1f  >+.......3.......<
0000100 00 14 07 d3 03 1a 10 20 46 64 00 00 00 00 00 00  >....... Fd......<
0000120 00 01 00 00 00 00 00 00 0f 3d ff ff ff ff ff ff  >.........=......<
0000140 ff ff ff ff ff ff ff ff ff ff 3f ec b5 a6 b9 50  >..........?....P<
0000160 ed 65 bf 9d 1e 2b 0b 7c 44 c2                    >.e...+.|D.<
0000172
```
but will probably occur any time there is no previous packets or the only packets fail to match the conditions.

Probably should be a failed test instead of the exception.

**Comment by sfhelsdon-dstl** [comment]
This situation is when a segment only contains postamble tables or end of segment tables. dev branch now has a fix for this. Should now detect case and report as an error.
