### ISSUE TITLE
IndexError on checking end record mark

### ISSUE THREAD

**Issue by bradh** [dstl/NPIF-Sleuth#4]
```
Traceback (most recent call last):
  File "./NPIF Sleuth.py", line 107, in <module>
    main()
  File "./NPIF Sleuth.py", line 101, in main
    retval = NPIF_Extract(fname)
  File "./NPIF Sleuth.py", line 86, in NPIF_Extract
    a.file_error_checks()
  File "/home/bradh/coding/NPIF-Sleuth/NPIF.py", line 5611, in file_error_checks
    self.check_end_record_mark()
  File "/home/bradh/coding/NPIF-Sleuth/NPIF.py", line 5787, in check_end_record_mark
    p = self.packets[-2]
IndexError: list index out of range
```

The relevant bit of code is:
``` python
        if d.hdr.tablecode == self.DT_End_Record_Marker_DT:
            p = self.packets[-2]
```

Occurs on this file:
```
0000000 0d 79 ab 21 6f 34 1a 72 b9 1c 03 00 02 30 00 00  >.y.!o4.r.....0..<
0000020 00 00 00 00 00 08 00 00 00 00 00 00 00 00 00 00  >................<
0000040 0f 3d 00 00 00 00 00 00 99 08 00 00 00 00 01 1e  >.=..............<
0000060 60 33                                            >`3<
0000062
```
(i.e. there is no previous packet)

I'm not sure if a file containing only a end of record marker is valid - couldn't find an explicit statement in the STANAG, but I think that either that case should be a test failure or be silently skipped.

**Comment by sfhelsdon-dstl** [comment]
By my reading its not strictly invalid, but likely to be very rare in practice. Either way, code updated in current dev branch to deal with this situation. It will now generate a warning if this situation arises when checking for conformance.
